name: check
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: reviewdog/action-setup@v1
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew spotlessCheck
      - run: ./gradlew lintDebug
      - run: ./gradlew detekt-extensions:test
      - run: ./gradlew deteKt
      - run: |
          find . -type f -name detekt.sarif -exec \
          jq -r ".runs[].results[] | select(.ruleId == \"detekt.extra-rules.ContextOrder\") | .locations[].physicalLocation.artifactLocation.uri" {} + | \
          sed "s|file://$PWD/||" | \
          sort > error_files.txt
      - run: git diff --name-only origin/main | sort > change_files.txt
      - name: ContextOrder 違反チェック
        run: "! join error_files.txt change_files.txt | grep '.'"
      # reviewdog
      - run: find . -type f -name detekt.sarif -exec npx @microsoft/sarif-multitool merge {} +
      - run: reviewdog -f=sarif -name="detekt" -reporter=github-pr-review < merged.sarif
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Unit Test
      - run: ./gradlew koverXmlReport
      # Codecov
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      # Dependency Tree Diff
      - id: dependency-diff
        name: Generate dependency diff
        uses: usefulness/dependency-tree-diff-action@v1
        with:
          project: 'androidApp'
        if: github.event_name == 'pull_request'
      - uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Dependency diff
        if: github.event_name == 'pull_request'
      - uses: peter-evans/create-or-update-comment@v2
        if: ${{ github.event_name == 'pull_request' && (steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null) }}
        with:
          body: |
            Dependency diff (customize your message here):
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
