name: check_ios
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check_ios:
    runs-on: macos-14
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - uses: gradle/gradle-build-action@v2
      - run: xcodebuild -version
      - uses: irgaly/setup-mint@v1
      # フォーマットチェック
      - run: mint run swiftformat --lint --exclude iosApp/build iosApp
      # ビルドチェック
      - run: xcodebuild -allowProvisioningUpdates -project iosApp.xcodeproj -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' -derivedDataPath ./build build
        working-directory: iosApp
