name: upload_incremental_build_time
on:
  push:
    branches:
      - main
jobs:
  upload_incremental_build_time:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
      - run: echo ${{ secrets.SERVICE_ACCOUNT_JSON }} | base64 -d > /tmp/credential.json
      - name: checkout previous merge commit
        run: git checkout `git log --merges -n 2 --pretty=format:"%H" | tail -n 1`
      - run: ./gradlew assembleDebug
      - run: git checkout main
      - run: ./gradlew assembleDebug -PuploadBuildTime=true
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "/tmp/credential.json"
