name: upload_incremental_build_time
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  upload_incremental_build_time:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - uses: gradle/gradle-build-action@v2
      - run: echo ${{ secrets.SERVICE_ACCOUNT_JSON }} | base64 -d > /tmp/credential.json
      - name: checkout previous merge commit
        run: git checkout `git log --merges -n 2 --pretty=format:"%H" | tail -n 1`
      - name: build previous merge commit
        run: ./gradlew assembleDebug
      - name: checkout current merge commit
        run: git checkout main
      - name: measure incremental build time
        run: |
          start_time=$(date +%s) &&
          ./gradlew assembleDebug &&
          end_time=$(date +%s) &&
          duration=$((end_time - start_time)) &&
          echo "duration=$duration" >> $GITHUB_ENV
      - name: upload incremental build time to BiqQuery
        run: |
          sql="INSERT INTO \`tfandkusu.kmm_github_search.build_time\`(created_at, duration, type) VALUES(CURRENT_TIMESTAMP(), $duration,\"incremental\")"
          bq query --nouse_legacy_sql $sql
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "/tmp/credential.json"
